export enum ActivityType {
  CHARLA_TECNICA = "CHARLA_TECNICA",
  RUEDA_DE_NEGOCIOS = "RUEDA_DE_NEGOCIOS",
  OTRO = "OTRO",
}

export enum DafoType {
  DEBILIDAD = "DEBILIDAD",
  AMENAZA = "AMENAZA",
  FORTALEZA = "FORTALEZA",
  OPORTUNIDAD = "OPORTUNIDAD",
}
